@startuml

title Diagramme de sequence de l'attaque du héros

participant "main" as main
participant "moteur : MoteurJeu" as moteur
participant "labyJeu : LabyJeu" as labyJeu
participant "personnage : Perso" as personnage
participant "monstre : Monstre" as monstre




activate main
    main -> moteur : setTaille(width, height)
    moteur --> main
    main -> moteur : setFPS(fps)
    moteur --> main
    main -> labyJeu : update(15, "Space")

    activate labyJeu
        activate personnage
            labyJeu -> personnage : attaquer(Monstre m)
            activate monstre
                personnage -> monstre : etreMort()
                monstre --> personnage
            deactivate monstre
            personnage --> labyJeu
        deactivate personnage

        labyJeu --> main
    deactivate labyJeu

    main -> moteur : launch(labyJeu, labyDessin)
    activate moteur
    moteur --> main
    deactivate moteur

deactivate main

@enduml