@startuml

title Diagramme de sequence de l'attaque du héros

participant "main" as main
participant "labyJeu : LabyJeu" as labyJeu
participant "personnage : Perso" as personnage
participant "monstre : Monstre" as monstre




activate main

    main -> labyJeu : update(15, "Space")

    activate labyJeu
        activate personnage
            labyJeu -> personnage : attaquer(Monstre m)
            labyJeu -> labyJeu : genererMonstre()
            activate monstre
                personnage -> monstre : perdrePv(int pv)
                personnage -> monstre : etreMort()
                monstre --> personnage
            deactivate monstre
            personnage --> labyJeu
        deactivate personnage

        labyJeu --> main
    deactivate labyJeu

deactivate main

@enduml