@startuml

class Labyrinthe{
    {static} +MUR : char
    {static} +PJ : char
    {static} +VIDE : char
    {static} +HAUT : String
    {static} +BAS : String
    {static} +GAUCHE : String
    {static} +DROITE : String
    +murs : boolean[][]

    +Labyrinthe(String nomFichier) : Labyrinthe
    {static}+getSuivant(int x, int y, String action) : int[]
    +deplacerPerso(String action) : void
    +etreFini() : boolean
    +getLenghtY() : int
    +getLenght() : int
    +getMur(int x, int y) : boolean


}
class Perso {
    -pos : Position
    +Perso(int dx, int dy) : Perso
    +etrePresent(int dx, int dy) : boolean
    +getPos() : Position
}

class PassageSecret {
    -pos : Position
    -ouvert : boolean
    +PassageSecret(int dx, int dy, BoutonPassage btn)
    +ouvrirPassage() : void
    +etreOuvert() : boolean
    +getPos() : Position
}

class BoutonPassage {
    -pos : Position
    -active : boolean
    +BoutonPassage(int dx, int dy)
    +activerBouton() : void
    +etreActive() : boolean
    +getPos() : Position
}

class Position {
    -x : int
    -y : int
    +getX() : int
    +getY() : int
}

Labyrinthe "1"-->"1" Perso : +pj
Labyrinthe "1"-->"*" PassageSecret : +passageSecret
PassageSecret "1"-->"1" BoutonPassage : +bouton


@enduml