@startuml
participant "main" as main
participant "labyJeu : LabyJeu" as labyJeu
participant "laby : Labyrinthe" as laby
participant "personnage : Perso" as personnage



activate main


    activate labyJeu
        main -> labyJeu : update(15.0, "Droite")
        labyJeu -> labyJeu : ajouterMonstre()
        activate laby
            activate personnage
                labyJeu -> laby : deplacerPerso()
                laby -> laby : int[] suivante = getSuivant(courante[0], courante[1], action)
                laby -> personnage : setX(suivante[0])
                personnage --> laby
                laby -> personnage : setY(suivante[1])
                personnage --> laby
                laby --> labyJeu
            deactivate personnage
        deactivate laby

    labyJeu --> main
    deactivate labyJeu



deactivate main

@enduml