@startuml
'https://plantuml.com/sequence-diagram

title Diagramme de séquence d'un passage secret qui se ferme à partir d'un bouton qui se situe à gauche du perso

participant "main" as main
participant "laby: Labyrinthe" as laby
participant "perso : Perso" as perso
participant "bouton : BoutonPassage" as bouton
participant "passageSecret : PassageSecret" as passageSecret

activate main
    activate laby
        main -> laby : deplacerPerso(Gauche)
        activate perso
        laby -> perso : memePositionPassageSecret()
        perso --> laby : true
        activate bouton
        laby -> bouton : activerPassage()
        activate passageSecret
            bouton -> passageSecret : ouvrirPassage()
            passageSecret --> bouton
        deactivate passageSecret
        bouton --> laby
        deactivate bouton
        laby --> main
    deactivate laby
deactivate main
@enduml