@startuml
participant "main" as main
participant "moteur : MoteurJeu" as moteur
participant "labyJeu : LabyJeu" as labyJeu
participant "labyDessin : LabyDessin" as labyDessin
participant "laby : Labyrinthe" as laby


activate main
    main -> moteur : setTaille(width, height)
    moteur --> main
    main -> moteur : setFPS(fps)
    moteur --> main
    create labyJeu
    main -> labyJeu : new
    create labyDessin
    main -> labyDessin : new

    activate labyJeu
        main -> labyJeu : update(15.0, "Droite")
        labyJeu -> labyJeu : ajouterMonstre()
        activate laby
            labyJeu -> laby : deplacerPerso()
            labyJeu -> laby : deplacerMonstre()
            laby -> laby : getSuivant(courante[0], courante[1], action)
            laby -> laby : deplacementPossible(suivante)
            laby --> labyJeu
        deactivate laby

    labyJeu --> main
    deactivate labyJeu

    main -> moteur : launch(labyJeu, labyDessin)
    activate moteur
    moteur -> main
    deactivate moteur

deactivate main

@enduml