@startuml

title Diagramme de Sequence de déplacement aléatoire de monstre

participant "main" as main
participant "labyJeu : LabyJeu" as labyJeu
participant "laby : Labyrinthe" as laby
participant "personnage : Perso" as personnage
participant "monstre : Monstre" as monstre




activate main


    activate labyJeu
        main -> labyJeu : update(15.0, "Droite")
        labyJeu -> labyJeu : ajouterMonstre()
        activate laby
            labyJeu -> laby : deplacerPerso("droite")
            activate personnage

                laby -> laby : int[] suivante = getSuivant(courante[0], courante[1], action)
                laby -> personnage : setX(suivante[0])
                personnage --> laby
                laby -> personnage : setY(suivante[1])
                personnage --> laby

            deactivate personnage
            laby -> laby : deplacerMonstre(value)
            activate monstre
                loop loop
                laby -> laby : int[] suivante = getSuivant(courante[0], courante[1], action)
                laby -> monstre : setX(suivante[0])
                monstre --> laby
                laby -> monstre : setX(suivante[1])
                monstre --> laby
                end

            deactivate monstre
            laby -> laby : deplacementPossible(suivante)
            laby --> labyJeu
        deactivate laby

    labyJeu --> main
    deactivate labyJeu



deactivate main

@enduml